export const runtimeApiContract = {
  factsSource: "backend-runtime-api",
  serverOwnedFacts: ["session", "timeline", "checkpoint", "context", "revision", "replay"],
  endpoints: [
    "POST /api/sessions",
    "GET /api/sessions/{id}",
    "POST /api/sessions/{id}/messages",
    "GET /api/sessions/{id}/messages",
    "PATCH /api/messages/{id}",
    "POST /api/messages/{id}/continue",
    "POST /api/messages/{id}/replay",
    "GET /api/messages/{id}/impact",
    "GET /api/sessions/{id}/timelines",
    "GET /api/timelines/{id}",
    "POST /api/timelines/{id}/activate",
    "GET /api/sessions/{id}/context",
    "POST /api/context-groups/{id}/pin",
    "POST /api/context-groups/{id}/unpin",
    "POST /api/context-groups/{id}/abstract",
    "POST /api/context-groups/{id}/evict",
    "POST /api/context-groups/{id}/restore",
    "PATCH /api/context-items/{id}",
    "GET /api/context-items/{id}/raw",
    "GET /api/context-items/{id}/revisions",
    "POST /api/templates",
    "GET /api/templates/{id}",
    "PUT /api/templates/{id}",
    "POST /api/templates/{id}/validate",
    "POST /api/templates/{id}/compile",
    "POST /api/templates/{id}/run",
    "GET /api/sessions/{id}/trace",
    "GET /api/checkpoints/{id}",
    "GET /api/checkpoints/{id}/state",
    "GET /api/messages/{id}/trace",
  ],
};

export const thirdPartyCandidates = [
  { packageName: "@assistant-ui/react", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "@xyflow/react", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "react-resizable-panels", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "@tanstack/react-query", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "msw", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "monaco-editor", runtimeFactOwner: false, contractChangesWhenDisabled: false },
  { packageName: "shadcn/ui", runtimeFactOwner: false, contractChangesWhenDisabled: false },
];
